### PR TITLE
Vue templates

### PR DESCRIPTION
**Pull request by ingdanielguerrero**
This new branch has a new `templates` directory to store those templates which are useful to mimic the Vuetify implementations, as first implementation I created a `DatePickert` object to test it, while we can decide which path choose, or until there is a solution for the Bug in Ipyvuetify [https://github.com/mariobuikhuizen/ipyvuetify/issues/88](url).
What do you think? I've created an example notebook to test it.

### CODE REVIEW

**Comment by 12rambau** [comment]
Can you move the pull request to develop ? 
The idea is the following : 
- we push our idea on develop 
- we add the appropriate tests in develop
- we push develop to master 
- the test evaluation is performed on master (I cannot change this behaviour)

**Comment by 12rambau** [comment]
I can't test you implementation because the templates folder is not available in the repository (I think `templates`is a keyword in the `.gitignore`)

**Comment by 12rambau** [comment]
As aggreed we will pull to develop instead of going for maser (to keep the test under control and allow ourself to make small mistakes)

**Comment by ingdanielguerrero** [comment]
yes sure, I'm gonna see what's happening with the templates folder, and why is not being installed along with the rest of the branch, then I'll merge it with develop for your review.

**Pull request closed without merging**
