### PR TITLE
Develop df

### PR DESCRIPTION
**Pull request by ingdanielguerrero**
- Refactoring alert, btn, and download button widget to solve issue #133.

- Added widget PasswordField.

### CODE REVIEW

**Comment by 12rambau** [comment]
Hi @ingdanielguerrero, good catch ! 

By doing that you removed my only custom widget example 😄  (https://sepal-ui.readthedocs.io/en/latest/tutorials/custom-widget.html) 

The build failed because of deprecations statements do you see the results of the build ?

**Comment by 12rambau** [comment]
Can you add a docstring to you password class following the [google napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) convention as in the other input classes ? 
It will be automatically updated in RTD 

Whenever you commit this change I will validate the pull request and I'll take care of the building issues myself

**Review by 12rambau — CHANGES_REQUESTED** [review]
Can you add a docstring to you password class following the [google napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) convention as in the other input classes ?
It will be automatically updated in RTD

**Comment by ingdanielguerrero** [comment]
Cool, I've added the docstring for widgets!

**Pull request merged**
