### PR TITLE
Clean only if necessary

### LINKED ISSUE #213: Aoi selector is taking too long to display widgets
The aoi view has a line that is forcing reset every widget method, which is needed to avoid duplicated data in the model.

https://github.com/12rambau/sepal_ui/blob/9899ab0a0d66e67ae397fd5c02a3c7f2aebc1621/sepal_ui/aoi/aoi_view.py#L301 

However, the `FileInput`  `reset` method takes some seconds to restore the `root` directory.

https://github.com/12rambau/sepal_ui/blob/9899ab0a0d66e67ae397fd5c02a3c7f2aebc1621/sepal_ui/sepalwidgets/sepalwidget.py#L69

So the result is that the entire aoi selector takes so long every time a new method is selected.

### PR DESCRIPTION
**Pull request by 12rambau**
Fix #213

### CODE REVIEW

**Comment by dfguerrerom** [comment]
Perfect!

**Review by dfguerrerom — COMMENTED** [review]
Perfect!

**Comment by 12rambau** [comment]
you closed it without merging ;-)

**Comment by dfguerrerom** [comment]
haha sorry ;)

**Pull request merged**
