### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by dfguerrerom**
Intended to solve #253

### CODE REVIEW

**Comment by dfguerrerom** [comment]
I forgot to mention, but this will fail on the test due to the change of the `default_asset` type, now it will require a list not a string. What do you think?

**Comment by dfguerrerom** [comment]
- I used an automatic translation to french, so I've zero clues if that makes sense ;).
- I've changed the asset type for asset info, would be more useful.

**Comment by 12rambau** [comment]
> I forgot to mention, but this will fail on the test due to the change of the `default_asset` type, now it will require a list not a string. What do you think?

I thik it's gonna lead to bugs to drop the support for string directly (i use it in every module that need a test dataset). But it's easy to test the type at the beggining and transform string into a list of string.

**Comment by 12rambau** [comment]
> * I used an automatic translation to french, so I've zero clues if that makes sense ;).

I'll correct the typos no worries

**Review by 12rambau — APPROVED** [review]

**Pull request merged**
