### PR TITLE
docs: add CLI tools

### LINKED ISSUE #444: add CLI to the documentation
everything is in the title

### PR DESCRIPTION
**Pull request by 12rambau**
Fix #444

### CODE REVIEW

**Comment by dfguerrerom** [comment]
I'm helping out with this doc build which was failing. 
Basically, the last one was failing because `bin` folder was not in the `sys.path`, and therefore the cli modules were inaccessible for the docs build, however, it seems like `autoprogram` doesn't do what we expected to do when the cli are installed as scripts with shebang, so I've changed them to python scripts —I've noted that is most frequent in that way. 
Now, I suppose that we have to add missing packages that are imported in the cli modules to make the build work, what do you think?

**Comment by 12rambau** [comment]
- add the bin folder to sys path 🎊 
- replace `p` by `parser`, that's a naming convention but you're right it's easier to get what it's about.

On the python scripts I'm curious, will it be still possible to do:
```
$ module_factory
```

or will we need to run 
```
$ python -m module_factory
```

?

**Comment by dfguerrerom** [comment]
> * add the bin folder to sys path 🎊
> * replace `p` by `parser`, that's a naming convention but you're right it's easier to get what it's about.
> 
> On the python scripts I'm curious, will it be still possible to do:
> 
> ```
> $ module_factory
> ```
> 
> or will we need to run
> 
> ```
> $ python -m module_factory
> ```
> 
> ?

I've tested on my side in a fresh env and it worked as it was working before, just $ command, so I think that entry point is managing this...
Now that they are python scripts, I think we can make specific tests, and validate them by capturing their stdout, what do you think?

(moved reply to this thread)

**Comment by 12rambau** [comment]
> Now that they are python scripts, I think we can make specific tests, and validate them by capturing their stdout, what do you think?

I would say test will be for another PR, but agreed

**Review by dfguerrerom — APPROVED** [review]
Do you think we can merge it now?

**Pull request merged**
